import "@/styles/globals.css";
import type { Metadata } from "next";
import clsx from "clsx";
import { fontSans } from "@/config/fonts";
import { ChildrenProps } from "@/types/nextjs";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<ChildrenProps>) => {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					className={clsx(
						'antialiased',
						fontSans.className,
					)}
					suppressHydrationWarning
				>
					<Providers>
						{children}
					</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
};

export default RootLayout;